build:
  version: "1.0"

accounts:
  message: "Welcome to Eazybank accounts related QA APIs"
  contactDetails:
    name: "Taewoo - QA Lead"
    email: "qa@google.com"
  onCallSupport:
    - (82) 8078-9876
    - (82) 8078-6789