spring:
  application:
    name: "configserver"
  profiles:
    active: git

    # active: native ??? ?? ????? classpath ? ???? ?? ?? ????.
    # active: native
  cloud:
    config:
      server:
        # ????? spring.cloud.config.server.native ? classpath, ?? ???? ???? ??? ????.
        # native:
        # search-locations: "file:///Users/ing9990/Documents/config-files/config"
        git:
          # ?? ?????? ??? ??? ????.
          uri: "https://github.com/ing9990/config-files.git"
          # ?? ???? ??? ??? ?? ??.
          default-label: "master"
          timeout: 5
          # ???? ?? ?????? ??? ?? ??
          clone-on-start: true
          # pull? ?? ?? (? ?? ??? ????? ??? ???)
          force-pull: true

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"

encrypt:
  key: d203bdab1cb64454878e745bdecc7c9d

server:
  port: 8071