spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "file:///Users/ing9990/Documents/config-files/config"

          # ?? ??? resources/config/ ???? ????.
          # search-locations: "classpath:/config"

server:
  port: 8071