server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

build:
  version: "1.0"

accounts:
  message: "Welcome to Eazybank accounts related local APIs"
  contactDetails:
    name: "Taewoo"
    email: "mail80782258@google.com"
  onCallSupport:
    - (82) 8078-12345
    - (82) 8078-54321